I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 214, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 214, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 319, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
TypeError: 'bool' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 214, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 214, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 319, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\display\core.py", line 2175, in interact
    self.start()
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\display\core.py", line 1033, in start
    self.set_mode()
  File "C:\Users\ASUS\Desktop\renpy-8.3.8.25052302+nightly-sdk\renpy\display\core.py", line 1357, in set_mode
    if draw.init(virtual_size):
  File "gl2draw.pyx", line 508, in renpy.gl2.gl2draw.GL2Draw.init
  File "gl2draw.pyx", line 556, in renpy.gl2.gl2draw.GL2Draw.on_resize
TypeError: 'bool' object is not callable

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
鶯鶯傳之渣男是你嗎? 0.2
Sun Jun  8 13:03:16 2025
